Addfriend routes and handler
TriAnh1995/assignment pull request #2
Opened 2023-11-01 07:03 UTC by TriAnh1995

- Add route in "routes" for AddFriend API
- Add "add_friends" function at Handler
- Add more validate functions in "validate"
- Change the name of some files for clarity

2023-11-01 10:24 UTC, loctrans3corp commented on api/internal/handler/add_friends.go
> +		} else {
why we need the `else` in here?

2023-11-01 10:26 UTC, loctrans3corp commented on api/internal/handler/validate.go
> +	if (len(f.Emails) < 2) || (f.Emails[0] == f.Emails[1]) {
what if the list emails have more than 2? maybe 3... 4 emails? still valid?

2023-11-01 10:27 UTC, loctrans3corp commented on api/internal/handler/validate.go
> +		return errors.New("The first email is blank")
how user know it is the first or the seconds email

2023-11-01 10:28 UTC, loctrans3corp commented on api/data/migration/0001_init.up.sql
> +    CONSTRAINT unique_friends UNIQUE (user_email_1, user_email_2)
why (user_email_1, user_email_2) not (user_email_2, user_email_1)

2023-11-01 10:30 UTC, loctrans3corp commented on api/internal/handler/validate.go
> +	validate() error
why we need interface in here?

2023-11-01 10:33 UTC, loctrans3corp reviewed
.idea/vcs.xml

this file is for what?

2023-11-02 02:53 UTC, TriAnh1995 commented on api/internal/handler/add_friends.go
> +		} else {
My apologies, this is one of my bad habits. At the beginning, I used to have problem when even in the case of Error happen, the success message still be printed, so i have to put "else" to avoid it.
But lately i learnt to use "return" to exit program when an error occurs, so we don't need to use "else" anymore, but i forgot to update my code.
I will fix it immediately

2023-11-02 02:54 UTC, TriAnh1995 commented on api/internal/handler/validate.go
> +	if (len(f.Emails) < 2) || (f.Emails[0] == f.Emails[1]) {
My apologies, that is a good point. I hadn't considered those issues while coding.
I will fix it immediately

2023-11-02 02:54 UTC, TriAnh1995 commented on api/internal/handler/validate.go
> +		return errors.New("The first email is blank")
I'm sorry but i don't understand the issue. Should the user, the one typing the request know which one is the first or second emails ??
Also, the input format {"friends":["...@example.com","...@example.com"]} doesn't clarify first and second input in the JSON.
Ao there is not much i can do here.
If you have any solution, please enlighnting me

2023-11-02 02:54 UTC, TriAnh1995 commented on api/data/migration/0001_init.up.sql
> +    CONSTRAINT unique_friends UNIQUE (user_email_1, user_email_2)
My apologies, I use CONSTRAINT to prevent the same frienship to be added in the database.
And from what i researched, it said that the order of the columns in the UNIQUE constraint does not matter.
Beside i have another function in repository package to check if the friendship already be added using query.
So this issue rarely come up during my testing.
But you're right, the CONSTRAIN doesn't work when you switch the positions of the values in both columns.
I will fix it immediately

2023-11-02 02:57 UTC, loctrans3corp commented on api/internal/handler/add_friends.go
> +		if err := h.ctrl.AddFriend(c.Request.Context(), input.Emails); err != nil {
you havent created the controler interface? u should create the interface fuction when calling like that..
There is no func for AddFriend right now.
![Uploading image.png…]()

2023-11-02 02:59 UTC, TriAnh1995 commented on api/internal/handler/validate.go
> +	validate() error
My apologize, you're right, we don't need that interface
I'll fix it imediately

2023-11-02 03:16 UTC, TriAnh1995 commented on api/internal/handler/add_friends.go
> +		if err := h.ctrl.AddFriend(c.Request.Context(), input.Emails); err != nil {
My apologises, I understand there is no AddFriend function on Controller package to be called.
i though we have to check this branch on Handler first and then after it got approved and merge, i would continue to add function on Controller later

2023-11-02 03:32 UTC, loctrans3corp commented on api/internal/handler/add_friends.go
> +		if err := h.ctrl.AddFriend(c.Request.Context(), input.Emails); err != nil {
no no... u need to create the interface controller function...
no need to create all just one function for interface that enough

2023-11-02 06:56 UTC, loctrans3corp commented on api/internal/handler/add_friends.go
> +	_ "github.com/goccy/go-json"
this one for what????

2023-11-03 07:08 UTC, nhan1603 requested changes

2023-11-03 07:08 UTC, nhan1603 commented on api/internal/handler/validate.go
> +	}
why do we need a for loop here ? Can reduce complexity by using if `(f.Emails[0] == "") || (f.Emails[1] == "")` since we checked for number of input in the previous step

2023-11-03 07:08 UTC, nhan1603 commented on api/internal/handler/validate.go
> +	}
Same here, no need for loop, can use if with two conditions separated by `||`

2023-11-03 07:08 UTC, nhan1603 commented on api/cmd/routes/routes.go
> +
Remove empty blank line

2023-11-03 07:08 UTC, nhan1603 commented on api/internal/handler/add_friends.go
> +
remove empty line

2023-11-03 07:25 UTC, merged