5 -  Block_User Controller
TriAnh1995/assignment pull request #20
Opened 2023-12-13 03:53 UTC by TriAnh1995

- Initializing Block_User Controller

2024-01-05 08:18 UTC, nhan1603 commented on api/internal/controller/block_users.go
> +		checkIfFollowed, err := i.repo.CheckIfBlocked(ctx, userEmails)
are you using the wrong function here?

2024-01-05 08:19 UTC, nhan1603 commented on api/internal/controller/block_users.go
> +		checkIfBlocked, err := i.repo.CheckIfFollowed(ctx, userEmails)
same here

2024-01-05 08:20 UTC, nhan1603 requested changes
See comments

2024-01-05 08:30 UTC, TriAnh1995 commented on api/internal/controller/block_users.go
> +		checkIfFollowed, err := i.repo.CheckIfBlocked(ctx, userEmails)
whoops, that my mistake. I will change the variable name.

2024-01-08 02:15 UTC, nhan1603 approved these changes

2024-01-09 02:18 UTC, merged