- AddFriend Repository
TriAnh1995/assignment pull request #4
Opened 2023-11-08 02:46 UTC by TriAnh1995

- Complete AddFriends API:
+  With two functions in Repository, including test files
+ Generate Friendship models in orm
+ Create SQL test data for table Friendship
+ Create error_message to contain messages received from database

2023-11-27 04:19 UTC, nhan1603 requested changes

2023-11-27 04:19 UTC, nhan1603 commented on .idea/sqldialects.xml
Don't commit idea config files

2023-11-27 04:19 UTC, nhan1603 commented on .idea/codeStyles/codeStyleConfig.xml
Don't commit idea config files

2023-11-27 04:19 UTC, nhan1603 commented on api/cmd/main.go
> +	_ "github.com/lib/pq"
why do we need to add this line ?

2023-11-27 04:19 UTC, nhan1603 commented on api/internal/handler/add_friends.go
> +		if err := h.ctrl.AddFriends(c.Request.Context(), input.Emails); err != nil {
we need to change the unit test file accordingly as the function name is change. Mocks might not be working properly.

2023-11-27 04:19 UTC, nhan1603 commented on api/internal/controller/add_friends.go
> +		}
write a separate private function and checks user email one by one instead of looping:
``` 
func checkEmail(ctx, repository, userEmail) error {
	checkEmailExist, err := i.repo.CheckUserByEmail(ctx, userEmail)
	if err != nil {
		return ServerError
	}
	if !checkEmailExist {
		return UserNotFound
	}
	return nil
}
```

2023-11-27 04:19 UTC, nhan1603 commented on api/internal/controller/add_friends.go
> +		if err = i.repo.AddFriendship(ctx, userEmails); err != nil {
Don't pass the slice directly into the database. Instead separate them
`i.repo.AddFriendship(ctx, userEmails[0], userEmails[1])`

2023-11-27 04:19 UTC, nhan1603 commented on api/internal/repository/add_friendship.go
> +	}
Don't pass the slice directly into the database. Instead separate them 
```
func (i RepoImplement) AddFriendship(ctx context.Context, firstEmail, secondEmail string) error
	createFriendShip := &orm.Friendship{
		UserEmail1: firstEmail,
		UserEmail2: secondEmail,
	}
```

2023-11-28 02:11 UTC, TriAnh1995 commented on api/cmd/main.go
> +	_ "github.com/lib/pq"
From my understanding the library ".../lib/pq" need to be imported in order to be able to connect to Postgres,
otherwise it would have got "Error when connect DBsql: unknown driver "postgres" (forgotten import?)"

2023-11-28 04:13 UTC, nhan1603 approved these changes
LGTM

2023-11-28 06:14 UTC, merged